package cliui

// These templates are only for human-facing rendering. Structured results,
// diagnostic report fields and generated SSH configuration remain unchanged.
var environmentCatalog = map[string]translation{
	"env.status.header":              {"Environment: %s\nState:       %s\nWorkspace:   %s\nAccess:      %s\n", "開発環境: %s\n状態:     %s\n作業場所: %s\nアクセス: %s\n"},
	"env.status.base":                {"Base:        %s\nRevision:    %s\n", "ひな形（Base）: %s\nリビジョン:     %s\n"},
	"env.status.stopped":             {"Workspace retained; this Environment is stopped.", "この開発環境は停止しています。作業データは保持されています。"},
	"env.list.empty":                 {"No Environments. Create one with haco env create --workspace <workspace> <name>.", "開発環境はありません。haco env create --workspace <workspace> <name> で作成してください。"},
	"env.list.header":                {"NAME\tWORKSPACE\tBASE", "名前\t作業場所\tひな形（Base）"},
	"env.list.next":                  {"\nUse haco open <name> to connect, or haco env status <name> to inspect runtime state.", "\n接続するには haco open <name>、状態を調べるには haco env status <name> を実行してください。"},
	"env.copy.result":                {"Environment %s: %s\n", "開発環境 %s: %s\n"},
	"env.copy.workspace":             {"Workspace: %s\n", "作業場所: %s\n"},
	"env.copy.oci":                   {"OCI: %s\n", "OCI: %s\n"},
	"env.copy.retained_snapshot":     {"Temporary snapshot retained: %s; inspect haco snapshot list before explicit deletion\n", "一時スナップショットを保持しています: %s。削除する前に haco snapshot list で確認してください。\n"},
	"env.copy.failed":                {"haco: Environment copy failed: %v\n", "haco: 開発環境のコピーに失敗しました: %v\n"},
	"env.import.failed":              {"haco: import failed: %v\n", "haco: 開発環境の取り込みに失敗しました: %v\n"},
	"env.import.destination":         {"Import destination: %s (%s)\n", "取り込み先: %s（%s）\n"},
	"env.import.retained_workspace":  {"Workspace retained: %s\n", "作業データを保持しています: %s\n"},
	"env.import.retained_oci":        {"OCI retained: %s\n", "OCIデータを保持しています: %s\n"},
	"env.import.completed":           {"Imported %s\n", "開発環境 %s を取り込みました。\n"},
	"env.import.offline":             {"Offline repositories: %s\n", "オフラインのリポジトリ: %s\n"},
	"env.export.failed":              {"haco: export failed: %v\n", "haco: 開発環境の書き出しに失敗しました: %v\n"},
	"env.export.retained_snapshot":   {"Temporary snapshot retained: %s\n", "一時スナップショットを保持しています: %s\n"},
	"env.export.completed":           {"Exported %s to %s\n", "開発環境 %s を %s に書き出しました。\n"},
	"env.doctor.header":              {"Environment: %s\nWorkspace: %s (%s)\nState: %s\n", "開発環境: %s\n作業場所: %s（%s）\n状態: %s\n"},
	"env.doctor.next":                {"  Next: %s\n", "  次の操作: %s\n"},
	"env.doctor.connection":          {"Connection: %s %s:%d -> %d\n", "接続: %s %s:%d -> %d\n"},
	"env.doctor.scope":               {"Local prerequisites only; external DNS, egress Policy and desktop reachability are not tested.", "環境内の前提条件のみを確認しています。外部DNS、外向き通信の承認ルール、デスクトップからの接続性は未検証です。"},
	"env.doctor.start":               {"Start the Environment with haco env start %s", "haco env start %s で開発環境を起動してください。"},
	"env.doctor.start_before_checks": {"Start the Environment before checking local services", "環境内のサービスを確認する前に、開発環境を起動してください。"},
	"env.doctor.workspace":           {"Inspect the Environment Workspace attachment; do not delete retained data", "開発環境へのWorkspaceの接続を確認してください。保持されているデータは削除しないでください。"},
	"env.doctor.dns":                 {"Inspect hacocoon-dns.service in the Environment; separately review network.resolve Policy", "開発環境内の hacocoon-dns.service を確認してください。network.resolve の承認ルールは別途確認してください。"},
	"env.doctor.ssh":                 {"Inspect the Environment ssh.service and rerun haco ssh setup %s", "開発環境内の ssh.service を確認し、haco ssh setup %s を再実行してください。"},
}
