package cliui

var detailCatalog = map[string]translation{
	"detail.doctor_env":         {"Optional Environment to diagnose; omission checks the Host. Diagnostics inspect and do not repair.", "調べる開発環境の名前。省略時はHostを確認します。診断では修復を実行しません。"},
	"detail.setup_env":          {"Optional Environment to set up; omission prepares the trusted Host. Existing saved setup is replayed when no update option is supplied.", "セットアップする開発環境。省略時は信頼済みHostを準備します。更新指定がなければ保存済みの手順を再実行します。"},
	"detail.setup_script":       {"Save and run a regular UTF-8 bash script (at most 1 MiB). Do not combine with --clear-script.", "通常のUTF-8 bashスクリプト（最大1MiB）を保存して実行します。--clear-scriptとは併用しません。"},
	"detail.setup_clear":        {"Remove the selected saved script without running it.", "選択した保存済みスクリプトを、実行せずに解除します。"},
	"detail.config_edit":        {"Edit a revision-bound configuration snapshot using VISUAL or EDITOR.", "VISUALまたはEDITORを使い、現在のrevisionに対応する設定を編集します。"},
	"detail.config_file":        {"Apply an edited snapshot produced by haco config. Stale revisions are refused.", "haco configで取得して編集した設定を適用します。古いrevisionは拒否します。"},
	"detail.approve_request":    {"Optional pending request identity. Omission opens the pending selection flow; reading the list does not approve anything.", "承認待ち要求の識別子。省略時は一覧から選択します。一覧の表示だけでは許可しません。"},
	"detail.reclaim_yes":        {"Confirm the selected reclamation or review without another prompt.", "選択した容量回収または結果確認を、追加入力なしで確定します。"},
	"detail.reclaim_status":     {"Inspect the saved result without starting another reclamation.", "新しい容量回収を開始せず、保存された結果を確認します。"},
	"detail.reclaim_review":     {"Retain evidence of an unsuccessful operation without starting or retrying reclamation. May reopen the managed WSL to check its identity. May be combined with --yes.", "失敗・中断した操作の証拠を保持します。容量回収は開始・再試行しません。対象確認のため管理WSLを開き直す場合があります。--yesと併用できます。"},
	"detail.reclaim_before":     {"Save active work first: running sessions disconnect during WSL stop/restart. Retained files are not deleted. Reopen Hacocoon and use --status afterward.", "先に作業を保存します。WSL停止・再開時に接続が切れます。保持ファイルは削除しません。再入場後に--statusで結果を確認します。"},
	"detail.host_cpu":           {"CPU count or unlimited. Omission uses the configured resource default.", "CPU数、またはunlimited。省略時は設定済みの資源上限を使います。"},
	"detail.host_memory":        {"Memory size (for example 4GiB) or unlimited. Omission uses the configured default.", "メモリ容量（例: 4GiB）、またはunlimited。省略時は設定済みの既定値を使います。"},
	"detail.host_pids":          {"Process count or unlimited. Omission uses the configured default.", "プロセス数、またはunlimited。省略時は設定済みの既定値を使います。"},
	"detail.host_root":          {"Root disk size (for example 20GiB) or unlimited. Omission uses the configured default.", "rootディスク容量（例: 20GiB）、またはunlimited。省略時は設定済みの既定値を使います。"},
	"help.arguments":            {"Arguments:", "位置引数:"},
	"help.options":              {"Options:", "オプション:"},
	"help.requirements":         {"Before running:", "実行前の確認:"},
	"detail.env_new":            {"Required name for the new development Environment.", "必須。新しく作る開発環境の名前。"},
	"detail.env":                {"Required existing Environment name. See haco env list.", "必須。既存の開発環境の名前。haco env listで確認できます。"},
	"detail.env_optional":       {"Optional Environment name; omission uses the command's selection flow.", "開発環境の名前。省略時はコマンドの選択案内に進みます。"},
	"detail.stopped":            {"Required source Environment; stop it with haco env stop first.", "必須。コピー元・書き出し元の開発環境。先にhaco env stopで停止します。"},
	"detail.copy_name":          {"Optional new Environment name; defaults to <source>-copy.", "新しい開発環境の名前。省略時は<source>-copy。"},
	"detail.import_name":        {"Optional new Environment name; defaults to <source>-imported.", "新しい開発環境の名前。省略時は<source>-imported。"},
	"detail.restore_name":       {"Optional new Environment name; omission generates a name for the restored Environment.", "復元して作る開発環境の名前。省略時は復元先の名前を生成します。"},
	"detail.snapshot":           {"Required saved snapshot identity from haco snapshot list.", "必須。haco snapshot listで確認した保存データの識別子。"},
	"detail.snapshot_env":       {"Optional Environment filter; omission lists all saved snapshots.", "表示する開発環境の名前。省略時はすべての保存データを一覧表示します。"},
	"detail.connection":         {"Required connection identity from the Environment status or network list.", "必須。環境の状態表示または通信一覧で確認した接続の識別子。"},
	"detail.archive_in":         {"Required existing .haco bundle. Import creates independent retained data.", "必須。既存の.hacoファイル。独立した保持データとして取り込みます。"},
	"detail.archive_out":        {"Optional new output file; defaults to <environment>.haco. Existing files are refused.", "書き出す新しいファイル。省略時は<environment>.haco。既存ファイルには上書きしません。"},
	"detail.repo_new":           {"Required local name for the source repository.", "必須。取り込むソースリポジトリに付ける名前。"},
	"detail.repo":               {"Required source repository name from haco repo list.", "必須。haco repo listで確認したソースリポジトリの名前。"},
	"detail.remote":             {"Required upstream Git URL. Read access does not authorize push.", "必須。取得元のGit URL。読み取りの許可だけではpushを許可しません。"},
	"detail.branch":             {"Required existing upstream branch used for the initial checkout.", "必須。最初にチェックアウトする、取得元に存在するブランチ。"},
	"detail.repos":              {"Required registered repository names, separated by commas. Register sources with haco repo clone first.", "必須。登録済みリポジトリ名をカンマで区切ります。先にhaco repo cloneでソースを登録します。"},
	"detail.repos_optional":     {"Repository names for preparing a new work reference. Existing references retain their repository membership.", "新しい作業場所を準備する際のリポジトリ名。既存の作業場所は登録済みの構成を使います。"},
	"detail.workspace_new":      {"Required name for the independent working copy.", "必須。独立した作業コピーに付ける名前。"},
	"detail.workspace":          {"Required retained Workspace name from haco workspace list.", "必須。haco workspace listで確認した保持作業データの名前。"},
	"detail.workspace_source":   {"Required existing work reference to copy. Its associated Environment must be stopped.", "必須。複製元の作業場所。関連する開発環境は停止しておきます。"},
	"detail.workspace_required": {"Required existing Workspace path or managed:<name>. Project files survive Environment deletion.", "必須。既存Workspaceのパス、またはmanaged:<name>。作業ファイルは環境の削除後も保持します。"},
	"detail.path":               {"Required existing directory where the work reference is written.", "必須。作業場所の設定を保存する既存ディレクトリ。"},
	"detail.work_name":          {"Name for the new work reference; generated when omitted.", "新しい作業場所の名前。省略時は生成します。"},
	"detail.base":               {"Optional Base name; omission uses the configured default.", "環境のひな形の名前。省略時は設定済みの既定値を使います。"},
	"detail.fork_base":          {"Optional Base for opening the copy; omission retains the source's Base selection.", "コピー先で使うひな形。省略時はコピー元の選択を引き継ぎます。"},
	"detail.oci":                {"OCI data: auto for automatic preparation, none to omit, or oci:<store> for a retained Store. The default is auto.", "OCIデータ。autoは自動準備、noneは省略、oci:<store>は保持済みStoreを使用。既定はauto。"},
	"detail.read_access":        {"Git reads and pushes are authorized separately. Choosing main for clone never grants unconditional main push.", "Gitの取得とpushは別々に許可します。mainをcloneしてもmainへのpushを無条件には許可しません。"},
	"detail.saved":              {"Optional saved rule: env/all allow or deny this scope; ask-env/ask-all ask again. Omission decides only this request.", "保存するルール。env/allはこの範囲を許可または拒否、ask-env/ask-allは毎回確認。省略時は今回の要求だけを判断します。"},
	"detail.request":            {"Required pending request identity from haco git pending. The decision remains bound to its exact ref and commits.", "必須。haco git pendingで確認した承認待ちの識別子。判断はそのrefとcommitにだけ対応します。"},
	"detail.base_name":          {"Required Base name from haco base list.", "必須。haco base listで確認したひな形の名前。"},
	"detail.base_delete":        {"Required built Base name or unambiguous retained fingerprint from haco base list --all.", "必須。haco base list --allで確認した作成済みひな形の名前、または一意に特定できるfingerprint。"},
	"detail.base_all":           {"Show retained built-image revisions. --json is available with --all.", "保持している作成済みイメージの各revisionを表示します。--jsonは--allと併用します。"},
	"detail.definition":         {"Required JSON Base definition file. Build steps run in an isolated Environment.", "必須。Base作成手順を記述したJSONファイル。手順は隔離した環境で実行します。"},
	"detail.store":              {"Required OCI Store name from haco plugin oci store list; omit the oci: prefix here.", "必須。haco plugin oci store listで確認したOCI Store名。ここではoci:を付けません。"},
	"detail.store_new":          {"Required name for the independent OCI Store; omit the oci: prefix.", "必須。独立したOCI Storeに付ける名前。oci:は付けません。"},
	"detail.store_from":         {"Copy from a retained Store name. Omission copies the trusted Host OCI area; the copy is independent.", "複製元の保持Store名。省略時は信頼済みHostのOCI領域から独立コピーします。"},
	"detail.image_target":       {"Environment or oci:<store> to inspect. Omit only when using --host.", "調べる開発環境、またはoci:<store>。--hostを使う場合は省略します。"},
	"detail.image":              {"Image ID or tag to remove; omit only with --unused.", "削除するイメージIDまたはタグ。--unusedを使う場合は省略します。"},
	"detail.unused_list":        {"List only images reported unused by the selected runtime.", "選択したruntimeで未使用と判断されたイメージだけを表示します。"},
	"detail.unused_delete":      {"Review and remove unused images; do not combine with an image argument.", "未使用イメージを確認して削除します。個別イメージの引数とは併用しません。"},
	"detail.runtime":            {"OCI runtime: nerdctl (default) or docker.", "OCIの実行基盤。既定はnerdctl。dockerも選択できます。"},
	"detail.host_images":        {"Use the trusted Host OCI area instead of an Environment or Store argument.", "環境・Storeの指定に代えて、信頼済みHostのOCI領域を使います。"},
	"detail.yes":                {"Confirm the reviewed deletion without prompting. Reference and ownership checks still apply.", "表示した対象の削除を、追加入力なしで確定します。参照・所有権の検査は省略しません。"},
	"detail.protocol":           {"Transport protocol: tcp (default) or udp.", "通信方式。既定はtcp。udpも選択できます。"},
	"detail.target_port":        {"Required destination port, from 1 to 65535.", "必須。接続先のポート番号（1〜65535）。"},
	"detail.target":             {"Required destination hostname/IP, registered Host service name or Environment name, according to --kind.", "必須。--kindに対応する接続先ホスト名／IP、登録Hostサービス名、または開発環境名。"},
	"detail.network_port":       {"Destination port from 1 to 65535. May be omitted for a registered Host service; otherwise required.", "接続先のポート番号（1〜65535）。登録済みHostサービスでは省略できます。それ以外は必須です。"},
	"detail.kind":               {"Destination kind: external (default), host or environment.", "接続先の種類。既定はexternal。host、environmentも選択できます。"},
	"detail.listen":             {"Client loopback listen address; defaults to 127.0.0.1:0 (automatic port).", "クライアントのloopback待受アドレス。既定は127.0.0.1:0（自動ポート）。"},
	"detail.duration":           {"Requested connection lifetime; defaults to 5m. UDP is limited to 5m; Policy limits also apply.", "要求する接続の有効時間。既定は5m。UDPの上限は5mで、承認ルールの上限も適用します。"},
	"detail.host_address":       {"Required explicit numeric IP address for the Host or Windows service.", "必須。HostまたはWindowsのサービスが待ち受けるIPアドレスを数値で指定します。"},
	"detail.service_new":        {"Required name for the Host service registration.", "必須。Hostサービスの登録名。"},
	"detail.service":            {"Required service name from haco network host list.", "必須。haco network host listで確認したサービス名。"},
	"detail.rule_env":           {"Required Environment name whose communication is being configured.", "必須。通信ルールを設定する開発環境の名前。"},
	"detail.decision":           {"Required rule decision: allow, ask or deny. DNS resolution never grants connection permission.", "必須。allow（許可）、ask（毎回確認）、deny（拒否）。名前解決の成功だけでは接続を許可しません。"},
	"detail.ttl":                {"Saved rule lifetime; defaults to 1h, at most 31 days.", "保存するルールの有効時間。既定は1h、最大31日。"},
	"detail.scope":              {"Saved scope: instance (default), environment or global. Broader scopes apply to future matching requests.", "保存範囲。既定はinstance。environment、globalは将来の一致する要求にも適用します。"},
	"detail.aws_env":            {"Environment making the request; inferred when exactly one exists.", "要求元の開発環境。環境が一つだけの場合は省略できます。"},
	"detail.aws_profile":        {"Trusted Host AWS profile; defaults to default. Credentials stay on the Host.", "信頼済みHostのAWS profile。既定はdefault。認証情報はHostに保持します。"},
	"detail.aws_region":         {"AWS region; omission uses the trusted Host profile.", "AWSのregion。省略時は信頼済みHostのprofile設定を使います。"},
	"detail.s3_prefix":          {"Required S3 bucket/prefix URL to list.", "必須。一覧を取得するS3 bucket／prefixのURL。"},
	"detail.s3_object":          {"Required S3 object URL to download.", "必須。ダウンロードするS3 objectのURL。"},
	"detail.download":           {"Required new destination file. Existing files and unsafe paths are refused.", "必須。保存先の新しいファイル。既存ファイルや安全でないパスは拒否します。"},
	"detail.open":               {"Environment name or work directory. Use . for the current project; omission opens the selection flow.", "開発環境の名前、または作業ディレクトリ。現在のプロジェクトは.で指定します。省略時は選択案内に進みます。"},
	"detail.client":             {"Client to open: vscode (default), ssh or none.", "開くクライアント。既定はvscode。ssh、noneも選択できます。"},
	"detail.preview_port":       {"Open this Environment HTTP port as an approved preview.", "環境のHTTPポートを、許可されたプレビューとして開きます。"},
	"detail.close_preview":      {"Close the preview selected with --port.", "--portで指定したプレビューを閉じます。"},
	"detail.no_browser":         {"Print the preview URL without opening a browser.", "ブラウザを起動せず、プレビューURLを表示します。"},
	"detail.command":            {"Required executable and arguments after --. Arguments are passed directly, not interpreted as Host shell code.", "必須。--の後に実行ファイルと引数を指定します。Hostのshell命令として解釈せず、そのまま渡します。"},
	"detail.retention":          {"Environment deletion keeps retained Workspace files, OCI data and snapshots. Deleting those resources is a separate operation.", "環境を削除しても、保持Workspaceのファイル・OCIデータ・snapshotは残ります。それらの削除は別操作です。"},
}
