package cliui

// Keep human-facing text separate from commands, JSON, identifiers and raw
// subprocess errors. Every entry has an English fallback and a Japanese message.
type translation struct {
	en string
	ja string
}

var catalog = map[string]translation{
	"error.logging":                  {"haco: invalid logging configuration", "haco: ログ設定が無効です。HACO_LOG_LEVELとHACO_LOG_FORMATを確認してください。"},
	"base.import.archive":            {"Uncompressed Incus container image tar with metadata.yaml and rootfs; at most 64 GiB. Source files stay unchanged.", "metadata.yamlとrootfsを含む非圧縮のIncusコンテナイメージtar。上限64 GiB。元ファイルは変更しません。"},
	"base.import.failed":             {"Base import did not complete. Check the archive, available storage and reported builder before retrying. A retry starts a new builder.", "Baseの取り込みは完了していません。アーカイブ、空き容量、表示された作成環境を確認してください。再試行は新しい作成環境から始まります。"},
	"base.import.retained":           {"Builder retained: %s (%s). Inspect haco env status before explicit cleanup.\n", "作成環境を保持: %s（%s）。haco env statusで確認してから明示的に整理してください。\n"},
	"base.import.ready":              {"Base %s is ready (%s). Create an Environment with --base %s.\n", "Base %sを取り込みました（%s）。--base %sで開発環境を作成できます。\n"},
	"base.packer_context":            {"Packer HCL2 directory with external scripts (requires --name), or a current JSON shell definition.", "外部スクリプトを含むPacker HCL2ディレクトリ（--nameが必要）、または現行のJSON shell定義。"},
	"base.packer_name":               {"Name of the Base to publish.", "作成するひな形の名前。"},
	"base.packer_from":               {"Starting Base; omit to use the default.", "元にするひな形。省略時は既定値。"},
	"base.builder_name":              {"Optional build Environment name for scoped network settings; existing Environments are never reused.", "通信設定の対象にするビルド用環境名（任意）。既存環境は再利用しません。"},
	"base.packer_output":             {"Include private failed-build output; it may contain script data.", "失敗したbuildの非公開出力を表示します。スクリプト内の情報を含み得ます。"},
	"base.packer_failed":             {"Check the HCL/scripts, Base tools and normal network approvals. Use --output for private build output. Review any retained builder before retrying.", "HCL・スクリプト、元のひな形のツール、通常のネットワーク承認を確認してください。build出力は--outputで確認できます。再試行前に残ったbuild環境を確認してください。"},
	"flags.usage":                    {"Usage of %s:", "%s の使い方:"},
	"help.usage":                     {"Usage:", "使い方:"},
	"help.commands":                  {"Commands:", "コマンド:"},
	"help.setup":                     {"Prepare the Host or replay project setup in an Environment", "Hostを準備する・開発環境でプロジェクトのセットアップを再実行する"},
	"help.aws":                       {"Use approved AWS operations with trusted Host authentication", "Hostの認証情報を使い、承認されたAWS操作を実行する"},
	"help.config":                    {"Inspect or edit approval policy configuration", "操作の承認ルールを確認・編集する"},
	"help.approve":                   {"Review a pending request and optionally save its Policy", "承認待ちの操作を確認する・必要に応じてルールを保存する"},
	"help.doctor":                    {"Diagnose the Physical Host through its controller", "設定や接続の問題を調べる"},
	"help.reclaim":                   {"Reclaim unused managed WSL disk space or inspect its result", "管理対象WSLの未使用ディスク領域を回収する・結果を確認する"},
	"help.env":                       {"Create, inspect and access development Environments", "開発環境を作る・一覧や状態を見る・接続する"},
	"help.snapshot":                  {"Save, restore, list and explicitly delete independent saved data", "データを保存・復元する・保存済みデータを一覧表示・削除する"},
	"help.run":                       {"Execute a command in a temporary Environment and clean up", "一時的な開発環境でコマンドを実行し、終了後に片付ける"},
	"help.ssh":                       {"Prepare desktop SSH keys and connection settings", "デスクトップ側のSSH鍵と接続設定を準備する"},
	"help.open":                      {"Open an Environment in a desktop client", "開発環境をエディタなどで開く"},
	"help.base":                      {"List and inspect Environment starting points", "開発環境のひな形（Base）の一覧・詳細を見る"},
	"help.plugin":                    {"Optional integrations, including persistent OCI Stores", "OCI Storeなどの追加機能を使う"},
	"help.repo":                      {"Clone a repository inside the trusted Host", "GitリポジトリをHostに取り込む"},
	"help.workspace":                 {"Prepare an independent managed repository copy", "開発用の独立した作業コピーを用意する"},
	"help.git":                       {"Connect Git and review pending push approvals", "Gitを接続する・pushの承認待ちを確認する"},
	"help.help":                      {"Show this help", "この使い方を表示する"},
	"help.version":                   {"Show Hacocoon version information", "Hacocoonのバージョン情報を表示する"},
	"help.footer":                    {"The product CLI is being rebuilt from the basic workflow outward.", "CLIは基本的な作業の流れから順に整備しています。"},
	"usage":                          {"Usage: %s", "使い方: %s"},
	"error.usage":                    {"haco: usage: %s", "haco: 使い方: %s"},
	"error.unknown_command":          {"haco: command %q is not available yet; run 'haco help'\n", "haco: コマンド %q は利用できません。'haco help' で使い方を確認してください。\n"},
	"error.controller":               {"haco: cannot open controller client", "haco: コントローラーに接続できません。"},
	"error.write_result":             {"haco: cannot write result", "haco: 結果を出力できません。"},
	"version.long":                   {"Hacocoon\n  checkpoint: %s\n  version: %s\n  commit: %s\n  built: %s\n", "Hacocoon\n  開発段階: %s\n  バージョン: %s\n  コミット: %s\n  ビルド日時: %s\n"},
	"host.notice":                    {"Entering trusted haco-host. Host authority is available here; use an Environment for ordinary development work.", "信頼済みの haco-host に入ります。ここでは Host 権限を利用できます。通常の開発作業には Environment を使用してください。"},
	"env.switch_base_disabled":       {"haco: switch-base is disabled. Create a new Environment with --base and the retained Workspace.", "haco: switch-baseは利用できません。--baseと保持Workspaceを指定し、新しい環境を作成してください。"},
	"flag.no_oci":                    {"skip automatic OCI Store copy and attachment", "OCI Storeの自動コピーと接続を行わない"},
	"flag.workspace":                 {"Workspace path on the controller", "コントローラー側のWorkspaceのパス"},
	"flag.base":                      {"logical Base name", "開発環境のひな形（Base）の名前"},
	"env.status.dns":                 {"Name resolution: %s\n", "名前解決: %s\n"},
	"env.dns.host":                   {"Host (normal)", "Host（通常）"},
	"env.dns.backend":                {"execution backend", "実行基盤側"},
	"env.dns.disabled":               {"disabled", "無効"},
	"env.dns.unknown":                {"unknown setting; inspect configuration", "不明な設定・構成を確認してください"},
	"flag.dns":                       {"name resolution: host (default), backend, disabled", "名前解決: host（通常）、backend、disabled（無効）"},
	"flag.resource":                  {"persistent resource to attach exclusively, e.g. oci:dev", "排他的に接続する永続リソース（例: oci:dev）"},
	"flag.ssh_key":                   {"client-owned SSH public key file", "クライアント側で管理するSSH公開鍵ファイル"},
	"flag.ssh_port":                  {"Physical Host loopback port (default: automatic)", "Physical Hostのループバックポート（既定: 自動）"},
	"flag.json":                      {"machine-readable result", "機械処理向けの結果を出力する"},
	"doctor.header":                  {"Hacocoon Host diagnostics\ncontroller: %q (commit %q, protocol %d)\n", "Hacocoon Hostの診断\nコントローラー: %q（コミット %q、プロトコル %d）\n"},
	"doctor.next":                    {"  Next: %s\n", "  次の操作: %s\n"},
	"approval.host_required":         {"haco: open approval review from the trusted Host", "haco: 承認の確認は信頼済みのHostから開いてください。"},
	"approval.flag_list":             {"list pending requests without deciding", "許可・拒否せずに承認待ちの一覧を表示する"},
	"approval.flag_json":             {"print the decision receipt as JSON", "判断の結果をJSONで出力する"},
	"approval.read_failed":           {"haco: cannot read pending approvals", "haco: 承認待ちの一覧を読み取れません。"},
	"approval.no_longer_pending":     {"haco: request is no longer pending", "haco: この操作は承認待ちではなくなっています。"},
	"approval.none":                  {"No pending approvals.", "承認待ちの操作はありません。"},
	"approval.choose":                {"Choose a request (blank cancels): ", "確認する操作の番号を入力してください（未入力で中止）: "},
	"approval.invalid_request":       {"haco: invalid approval request", "haco: 承認リクエストが不正です。"},
	"approval.not_submitted":         {"haco: approval answer was not submitted", "haco: 承認の回答は送信されませんでした。"},
	"approval.outcome_failed":        {"haco: review outcome unavailable or unsuccessful for %q; inspect Policy and audit before retrying\n", "haco: %q の判断結果を確認できないか、処理に失敗しました。再試行する前にPolicyと監査記録を確認してください。\n"},
	"approval.receipt_mismatch":      {"haco: approval receipt does not match the request", "haco: 承認結果がリクエストと一致しません。"},
	"approval.unconfirmed":           {"Request outcome is not confirmed.", "操作の結果を確認できていません。"},
	"approval.denied":                {"Denied.", "拒否しました。"},
	"approval.approved":              {"Approved.", "許可しました。"},
	"approval.completed_unconfirmed": {"Capability completed; final confirmation failed.", "操作は完了しましたが、最終確認に失敗しました。"},
	"approval.not_executed":          {"Request was not executed.", "操作は実行されませんでした。"},
	"approval.execution_failed":      {"Request execution failed.", "操作の実行に失敗しました。"},
	"approval.allow_environment":     {"allow this scope in this Environment", "この範囲の操作をこのEnvironmentで許可する"},
	"approval.deny_environment":      {"deny this scope in this Environment", "この範囲の操作をこのEnvironmentで拒否する"},
	"approval.ask_environment":       {"ask every time for this scope in this Environment", "この範囲の操作をこのEnvironmentで毎回確認する"},
	"approval.allow_global":          {"allow this scope in all Environments", "この範囲の操作をすべてのEnvironmentで許可する"},
	"approval.deny_global":           {"deny this scope in all Environments", "この範囲の操作をすべてのEnvironmentで拒否する"},
	"approval.ask_global":            {"ask every time for this scope in all Environments", "この範囲の操作をすべてのEnvironmentで毎回確認する"},
	"approval.saved_policy":          {"Saved Policy:", "保存した承認ルール:"},
	"approval.request_id":            {"Request: %q\n", "リクエスト: %q\n"},
	"approval.prompt_header":         {"Approve capability %s action=%s resource=%s environment=%s", "次の操作の承認を確認します: capability=%s action=%s resource=%s environment=%s"},
	"approval.prompt_scope":          {" future-scope=%s/%s resource=%s", " 保存するルールの範囲=%s/%s resource=%s"},
	"approval.prompt_reason":         {" reason=%s? [%s] ", " 理由=%s [%s] "},
	"approval.options_once":          {"y/N", "y=今回だけ許可 / N=今回だけ拒否（未入力は拒否）"},
	"approval.options_persistent":    {"y/N; 1=allow this Environment, 2=deny this Environment, 3=allow all Environments, 4=deny all Environments, 5=ask every time in this Environment, 6=ask every time in all Environments", "y/N（今回のみ、未入力は拒否）; 1=この範囲をこのEnvironmentで許可, 2=この範囲をこのEnvironmentで拒否, 3=この範囲をすべてのEnvironmentで許可, 4=この範囲をすべてのEnvironmentで拒否, 5=この範囲をこのEnvironmentで毎回確認, 6=この範囲をすべてのEnvironmentで毎回確認"},
	"approval.options_global":        {"y/N; 3=allow all Environments, 4=deny all Environments, 6=ask every time in all Environments", "y/N（今回のみ、未入力は拒否）; 3=この範囲をすべてのEnvironmentで許可, 4=この範囲をすべてのEnvironmentで拒否, 6=この範囲をすべてのEnvironmentで毎回確認"},
}
