package cliui

var commandCatalog = map[string]translation{
	"daily.unknown_state":              {"Completion is not confirmed; resource state is unknown until inspected. Do not assume cleanup or retry succeeded.", "完了は確認できていません。状態を確認するまで、削除や再試行が成功したと判断しないでください。"},
	"daily.inspect":                    {"Next: haco env status %s; haco doctor %s. Inspect before retrying or deleting retained data.\n", "次の操作: haco env status %s、haco doctor %s で状態を確認してください。再試行や保持データの削除は確認後に行ってください。\n"},
	"daily.ssh_policy":                 {"If the Base lacks sshd, SSH preparation needs package access under the current Env Policy. In trusted haco-host, inspect haco approve --list and haco config; review the package endpoints before changing Policy. No approval or package failure is inferred from this error.", "ひな形にsshdがない場合、SSH準備には現在の承認ルールでパッケージ取得が必要です。信頼済みhaco-hostで haco approve --list と haco config を確認し、取得先を確認してからルールを変更してください。このエラーだけでは承認やパッケージ取得の失敗と断定できません。"},
	"daily.journal":                    {"Diagnostics (WSL/Linux Physical Host, administrator): journalctl -u haco-controller.service --since '30 minutes ago' --no-pager", "詳細診断（WSL/LinuxのPhysical Host、管理者）: journalctl -u haco-controller.service --since '30 minutes ago' --no-pager"},
	"daily.confirmation":               {"No changes made: confirmation requires a terminal; review the target and use --yes for scripts.", "変更していません。確認には端末が必要です。スクリプトでは対象を確認したうえで --yes を指定してください。"},
	"daily.delete":                     {"Delete Env %q: removes its runtime/root filesystem and connections. Workspace files, OCI Stores and independent snapshots remain. Use stop to keep the Env for tomorrow.\n", "環境 %q を削除します。環境内のrootfsと接続を削除し、Workspace・OCIデータ・独立snapshotを保持します。環境も残して次回再開する場合はstopを使ってください。\n"},
	"daily.next_open":                  {"Next: haco open %s (desktop) or haco env status %s.\n", "次の操作: haco open %s で接続するか、haco env status %s で状態を確認してください。\n"},
	"daily.resume":                     {"Resume: haco env start %s, then haco open %s.\n", "再開するには haco env start %s、続いて haco open %s を実行してください。\n"},
	"daily.retained":                   {"Review retained data: haco workspace list; haco plugin oci store list; haco snapshot list.", "保持データの確認: haco workspace list、haco plugin oci store list、haco snapshot list。"},
	"notification.inspect_failure":     {"Inspect haco doctor, haco approve --list and haco config. Similar failures are grouped for one minute.", "haco doctor、haco approve --list、haco config で確認してください。同種の失敗通知は1分間まとめます。"},
	"command.env":                      {"Create, inspect and connect to development environments", "開発環境を作る・調べる・接続する"},
	"command.env.list":                 {"List development environments", "開発環境を一覧で確認する"},
	"command.env.create":               {"Create an environment with a required Workspace; OCI is automatic unless disabled", "作業場所を指定して環境を作る。OCIは自動準備、--no-ociで省略"},
	"command.env.status":               {"Inspect runtime state and retained working data", "環境の状態と保持している作業データを確認する"},
	"command.env.start":                {"Resume a stopped environment", "停止中の環境で作業を再開する"},
	"command.env.stop":                 {"Stop work and retain the environment and its data", "環境と作業データを残して停止する"},
	"command.env.delete":               {"Delete the runtime; retain Workspace, OCI data and snapshots", "環境を削除し、Workspace・OCIデータ・snapshotを保持する"},
	"command.env.ssh":                  {"Prepare access using a client-owned public key; port defaults to automatic", "クライアントの公開鍵で接続を準備する。ポートは既定で自動選択"},
	"command.env.ssh-config":           {"Print SSH connection configuration", "SSH接続設定を表示する"},
	"command.env.disconnect":           {"Revoke an existing connection", "既存の接続を解除する"},
	"command.env.forward":              {"Forward a Physical Host loopback port; protocol defaults to TCP", "Physical Hostのloopbackから転送する。既定はTCP"},
	"command.env.copy":                 {"Independently copy a stopped environment and retained data", "停止中の環境と保持データを独立コピーする"},
	"command.env.export":               {"Export stopped managed data; destination defaults to <env>.haco", "停止中の管理対象データを書き出す。既定は<env>.haco"},
	"command.env.import":               {"Import independently; default name is <source>-imported", "独立した環境へ取り込む。既定名は<source>-imported"},
	"command.repo":                     {"Manage trusted Host source repositories", "信頼済みHostの取得元リポジトリを管理する"},
	"command.repo.clone":               {"Fetch one existing upstream branch into a source repository", "既存ブランチを取得して作業のコピー元にする"},
	"command.repo.list":                {"List source repositories", "取得済みのコピー元を一覧表示する"},
	"command.repo.delete":              {"Review and delete an unused source repository", "未使用のコピー元を確認して削除する"},
	"command.workspace":                {"Prepare, reopen and fork retained working sets", "保持する作業セットを準備・再開・分岐する"},
	"command.workspace.create":         {"Create independent working copies of registered repositories", "登録済みリポジトリから独立した作業コピーを作る"},
	"command.workspace.prepare":        {"Associate a directory with retained work without moving its files", "既存ファイルを移動せず、ディレクトリと保持作業を関連付ける"},
	"command.workspace.fork":           {"Fork one stopped working set into independent data", "停止中の作業セットから独立したデータへ分岐する"},
	"command.workspace.list":           {"List retained working data", "保持中の作業データを一覧表示する"},
	"command.workspace.delete":         {"Review and delete unreferenced working data", "参照されていない作業データを確認して削除する"},
	"command.git":                      {"Connect ordinary Git and review push proposals", "通常のGitを接続しpushの変更内容を確認する"},
	"command.git.connect":              {"Connect the environment to its registered Git source", "環境を登録済みのGit取得元へ接続する"},
	"command.git.pending":              {"List pending push proposals", "確認待ちのpushを一覧表示する"},
	"command.git.approve":              {"Approve the exact pending push; saving a scope is optional", "確認したpushだけを承認する。許可範囲の保存は任意"},
	"command.git.deny":                 {"Deny the pending push; saving a scope is optional", "確認待ちのpushを拒否する。拒否範囲の保存は任意"},
	"command.base":                     {"Choose or build starting contents for an environment", "環境のひな形を選ぶ・作る"},
	"command.base.list":                {"List available starting points", "利用できるひな形を一覧表示する"},
	"command.base.inspect":             {"Inspect a starting point and its revision", "ひな形とそのリビジョンを確認する"},
	"command.base.build":               {"Build a Base from its definition", "定義ファイルからひな形を作成する"},
	"command.base.delete":              {"Review and delete an owned unused Base image", "所有する未使用のひな形イメージを確認して削除する"},
	"command.snapshot":                 {"Save and restore independent stopped data", "停止中のデータを独立して保存・復元する"},
	"command.snapshot.create":          {"Save one stopped environment and its managed data", "停止中の環境と管理対象データを保存する"},
	"command.snapshot.list":            {"List saved snapshots", "保存済みのsnapshotを一覧表示する"},
	"command.snapshot.restore":         {"Restore independent data into a new environment", "独立したデータを新しい環境へ復元する"},
	"command.snapshot.delete":          {"Delete one explicitly selected saved snapshot", "選択した保存snapshotを削除する"},
	"command.plugin":                   {"Use optional developer integrations", "任意の開発用連携を利用する"},
	"command.plugin.oci":               {"Inspect and manage optional retained container data", "任意のコンテナ保持データを確認・管理する"},
	"command.plugin.oci.store":         {"Manage retained container stores", "保持しているコンテナデータ領域を管理する"},
	"command.plugin.oci.store.list":    {"List retained stores", "保持データ領域を一覧表示する"},
	"command.plugin.oci.store.inspect": {"Inspect a retained store", "保持データ領域を確認する"},
	"command.plugin.oci.store.create":  {"Create an independent retained store", "独立した保持データ領域を作成する"},
	"command.plugin.oci.store.delete":  {"Review and delete an unused owned store", "所有する未使用の保持データ領域を確認して削除する"},
	"command.plugin.oci.image":         {"Inspect and remove container images", "コンテナイメージを確認・削除する"},
	"command.plugin.oci.image.list":    {"List images in the selected runtime", "選択したruntimeのイメージを一覧表示する"},
	"command.plugin.oci.image.delete":  {"Review selected images before explicit deletion", "選択したイメージを確認して削除する"},
	"command.network":                  {"Connect authorized services and inspect active connections", "許可したサービスへ接続し、接続状態を確認する"},
	"command.network.tcp":              {"Open a policy-controlled TCP listener", "承認ルールに従うTCP接続口を開く"},
	"command.network.udp":              {"Open a policy-controlled UDP listener", "承認ルールに従うUDP接続口を開く"},
	"command.network.list":             {"Inspect active connection authority and expiry", "接続の許可範囲と期限を確認する"},
	"command.network.revoke":           {"Revoke an active connection", "実行中の接続を取り消す"},
	"command.network.host":             {"Register explicitly selected Host services", "明示的に選択したHostサービスを登録する"},
	"command.network.host.list":        {"List registered Host services", "登録したHostサービスを一覧表示する"},
	"command.network.host.add":         {"Register an exact service address; this does not grant access", "正確なサービス宛先を登録する。登録だけでは通信を許可しない"},
	"command.network.host.remove":      {"Remove a registered service", "サービス登録を解除する"},
	"command.network.rule":             {"Set the reviewed network rule and lifetime", "確認した接続ルールと有効期限を設定する"},
	"command.aws":                      {"Use approved AWS operations", "承認されたAWS操作を利用する"},
	"command.aws.s3":                   {"List and download selected S3 objects", "選択したS3オブジェクトを一覧・取得する"},
	"command.aws.s3.ls":                {"List approved S3 objects using Host authentication", "Host側の認証で許可されたS3オブジェクトを一覧表示する"},
	"command.aws.s3.cp":                {"Download one approved object without overwriting a file", "承認したオブジェクトを既存ファイルを上書きせず取得する"},
	"command.ssh":                      {"Prepare desktop-owned SSH access", "デスクトップ側にSSH接続を準備する"},
	"command.ssh.setup":                {"Prepare desktop keys and settings; blank terminal selection cancels", "デスクトップの鍵と設定を準備する。端末の空選択で中止"},
	"command.open":                     {"Open or resume work; directory preparation requires explicit repositories", "作業を開く・再開する。新しいディレクトリでは取得元の明示が必要"},
	"help.example":                     {"Example:", "実行例:"},
}
