package cliui

// Operation messages describe human-facing consequences. Resource identities,
// backend errors, state tokens and JSON values are never translated here.
var operationCatalog = map[string]translation{
	"operation.failed":              {"haco: operation failed:", "haco: 操作に失敗しました。詳細:"},
	"workspace.duplicate":           {"haco: duplicate Workspace identity", "haco: Workspaceの識別情報が重複しています。削除せず、一覧を確認してください。"},
	"workspace.missing":             {"haco: Workspace not found", "haco: Workspaceが見つかりません。haco workspace listで名前を確認してください。"},
	"workspace.busy":                {"haco: Workspace is referenced by an Environment or unfinished lease; delete the Environment first", "haco: 環境または未完了の利用予約がこのWorkspaceを使用しています。先に環境の状態と削除結果を確認してください。"},
	"workspace.incomplete":          {"haco: unfinished creation requires inspection; no data deleted", "haco: 作成が完了していません。状態の確認が必要です。データは削除していません。"},
	"workspace.delete_warning":      {"This deletes every repository and file in this Workspace, including uncommitted, untracked and unpushed work. Saved snapshots, OCI Stores and source repositories remain.", "このWorkspace内のすべてのリポジトリとファイルを削除します。未コミット・未追跡・未pushの作業も消えます。保存済みsnapshot、OCI Store、取得元リポジトリは残ります。"},
	"workspace.delete_prompt":       {"Delete this Workspace? [y/N] ", "このWorkspaceを削除しますか？ [y=削除 / N=保持（未入力は保持）] "},
	"workspace.retained":            {"Workspace retained.", "Workspaceを保持しました。"},
	"workspace.delete_failed":       {"haco: %v; ownership record retained if cleanup is incomplete\n", "haco: %v。後片付けが完了していない場合は所有権の記録を保持します。\n"},
	"workspace.deleted":             {"Workspace deleted; saved snapshots, OCI Stores and source repositories retained", "Workspaceを削除しました。保存済みsnapshot、OCI Store、取得元リポジトリは保持しています。"},
	"workspace.columns":             {"TYPE\tNAME\tMANAGED ID\tSTATE\tREPOSITORIES\tENVIRONMENTS\tSAVED SNAPSHOTS (independent)\tOCI STORES (retained)", "種類\t名前\t管理ID\t状態\tリポジトリ\t使用中の環境\t保存済みsnapshot（独立）\tOCI Store（保持）"},
	"source.missing":                {"haco: source repository not found", "haco: 取得元リポジトリが見つかりません。haco repo listで名前を確認してください。"},
	"source.busy":                   {"haco: referenced by Workspace Git routing; retained", "haco: WorkspaceのGit接続が使用しています。取得元リポジトリを保持しました。"},
	"source.incomplete":             {"haco: incomplete preparation requires inspection; retained", "haco: 準備が完了していません。状態を確認してください。データは保持しています。"},
	"source.delete_warning":         {"This deletes the selected Host source repository and its local Git data. Remote repositories, Workspaces, OCI Stores and independent snapshots remain.", "選択したHost側の取得元リポジトリと、そのローカルGitデータを削除します。リモートリポジトリ、Workspace、OCI Store、独立したsnapshotは残ります。"},
	"source.delete_prompt":          {"Delete this source repository? [y/N] ", "この取得元リポジトリを削除しますか？ [y=削除 / N=保持（未入力は保持）] "},
	"source.retained":               {"Source retained.", "取得元リポジトリを保持しました。"},
	"source.deleted":                {"Source repository deleted; remote and independent data retained", "取得元リポジトリを削除しました。リモートと独立したデータは保持しています。"},
	"source.columns":                {"TYPE\tNAME\tOWNER\tSTATE\tREMOTE\tBRANCH\tWORKSPACE USERS", "種類\t名前\t所有者\t状態\tリモート\tブランチ\t使用中のWorkspace"},
	"store.duplicate":               {"haco: duplicate Store identity", "haco: OCI Storeの識別情報が重複しています。削除せず、一覧を確認してください。"},
	"store.missing":                 {"haco: Store not found", "haco: OCI Storeが見つかりません。haco plugin oci store listで名前を確認してください。"},
	"store.references_unavailable":  {"haco: Store references unavailable", "haco: OCI Storeの使用状況を確認できません。削除せず、状態を確認してください。"},
	"store.busy":                    {"haco: Store is referenced or is the protected Host source; retained", "haco: このOCI Storeは使用中、または保護対象のHost取得元です。データを保持しました。"},
	"store.incomplete":              {"haco: incomplete Store creation requires inspection; retained", "haco: OCI Storeの作成が完了していません。状態を確認してください。データは保持しています。"},
	"store.delete_warning":          {"This deletes all images, container metadata, build cache and persistent data in this Store. Workspace files, the Host source and independent saved snapshots remain.", "このOCI Store内のすべてのイメージ、コンテナ管理情報、ビルドキャッシュ、永続データを削除します。Workspaceのファイル、Hostの取得元、独立した保存済みsnapshotは残ります。"},
	"store.delete_prompt":           {"Delete this OCI Store? [y/N] ", "このOCI Storeを削除しますか？ [y=削除 / N=保持（未入力は保持）] "},
	"store.retained":                {"Store retained.", "OCI Storeを保持しました。"},
	"store.deleted":                 {"OCI Store deleted; Workspace, Host source and independent snapshots retained", "OCI Storeを削除しました。Workspace、Hostの取得元、独立したsnapshotは保持しています。"},
	"store.columns":                 {"TYPE\tNAME\tMANAGED ID\tOWNER\tSTATE\tROLE\tWORKSPACE\tENVIRONMENTS\tPENDING COPIES\tSAVED SNAPSHOTS (independent)", "種類\t名前\t管理ID\t所有者\t状態\t役割\tWorkspace\t使用中の環境\t未完了のコピー\t保存済みsnapshot（独立）"},
	"base.ambiguous":                {"haco: ambiguous Base; select a longer fingerprint from 'haco base list --all'", "haco: 複数のBaseが一致します。haco base list --allから、より長いfingerprintを指定してください。"},
	"base.missing":                  {"haco: built Base not found; use 'haco base list --all' for retained revisions", "haco: 作成済みBaseが見つかりません。haco base list --allで保持されている版を確認してください。"},
	"base.busy":                     {"haco: Base has Environment or protected alias references; image retained", "haco: 環境または保護対象の別名がこのBaseを参照しています。イメージを保持しました。"},
	"base.delete_warning":           {"This deletes the selected local Base image and its aliases. Existing Workspace, OCI and independent snapshot data remain. This revision cannot be used for new creates afterward.", "選択したローカルのBaseイメージとその別名を削除します。既存のWorkspace、OCI、独立したsnapshotのデータは残ります。削除後はこの版で新しい環境を作成できません。"},
	"base.delete_prompt":            {"Delete this Base image? [y/N] ", "このBaseイメージを削除しますか？ [y=削除 / N=保持（未入力は保持）] "},
	"base.retained":                 {"Base retained.", "Baseを保持しました。"},
	"base.deleted":                  {"Base image deleted; Workspace, OCI and independent snapshots retained", "Baseイメージを削除しました。Workspace、OCI、独立したsnapshotは保持しています。"},
	"base.columns":                  {"TYPE\tNAME\tFINGERPRINT\tBUILD OWNER\tCURRENT\tENVIRONMENTS\tNATIVE USERS\tPROTECTED ALIASES\tSAVED SNAPSHOTS (independent)", "種類\t名前\tfingerprint\t作成所有者\t現在の版\t使用中の環境\t基盤上の利用者\t保護対象の別名\t保存済みsnapshot（独立）"},
	"image.invalid_review":          {"haco: invalid image review identity", "haco: イメージの確認対象が一致しません。削除せず、一覧を取得し直してください。"},
	"image.duplicate_review":        {"haco: invalid or duplicate image review identity", "haco: イメージの確認情報が不正または重複しています。削除せず、一覧を確認してください。"},
	"image.none_unused":             {"No images without container users; nothing deleted", "コンテナに使われていないイメージはありません。何も削除していません。"},
	"image.missing":                 {"haco: image not found; use image list to review exact IDs and tags", "haco: イメージが見つかりません。image listで正確なIDとタグを確認してください。"},
	"image.ambiguous":               {"haco: ambiguous image selection", "haco: 複数のイメージが一致します。一覧で対象を確認し、正確なIDを指定してください。"},
	"image.busy":                    {"haco: image is referenced by a container; retained", "haco: コンテナがこのイメージを使用しています。イメージを保持しました。"},
	"image.unused_warning":          {"Selection includes tagged images with no running or stopped container users. This is not an estimate of reclaimable bytes.", "実行中・停止中のコンテナが使っていない、タグ付きイメージも選択対象です。表示は回収可能な容量の見積もりではありません。"},
	"image.host_warning":            {"This changes the Host source used for future Store copies. Existing independent copies remain.", "今後のOCI Storeコピーに使うHost取得元を変更します。既存の独立したコピーは残ります。"},
	"image.delete_warning":          {"Delete this image from the selected Store. Independent copies, saved snapshots and remote registry images remain. The runtime may refuse images with multiple tags or other references; no force is used.", "選択したOCI Storeからこのイメージを削除します。独立したコピー、保存済みsnapshot、リモートレジストリのイメージは残ります。複数タグや他の参照がある場合、実行基盤が削除を拒否することがあります。強制削除は行いません。"},
	"image.delete_prompt":           {"Delete the reviewed image(s)? [y/N] ", "確認したイメージを削除しますか？ [y=削除 / N=保持（未入力は保持）] "},
	"image.retained":                {"Image retained.", "イメージを保持しました。"},
	"image.delete_failed":           {"haco: deletion stopped after %d of %d images: %v\n", "haco: %d / %d 件を削除した後に停止しました。詳細: %v\n"},
	"image.deleted":                 {"OCI image deleted: %s\n", "OCIイメージを削除しました: %s\n"},
	"image.host_target":             {"Target: managed Host source", "対象: 管理対象のHost取得元"},
	"image.detached_target":         {"Target: retained Store via a disposable Environment", "対象: 保持されているOCI Store（使い捨て環境から操作）"},
	"image.environment":             {"Environment: %q (generation %q)\n", "環境: %q（作成世代 %q）\n"},
	"image.details":                 {"Store: %q (owner %q, %s)\nRuntime: %q\nSaved snapshots (independent): %q\n", "OCI Store: %q（所有者 %q、%s）\n実行基盤: %q\n保存済みsnapshot（独立）: %q\n"},
	"image.columns":                 {"TYPE\tIMAGE ID\tTAGS\tDIGESTS\tCONTAINER USERS", "種類\tイメージID\tタグ\tダイジェスト\t使用中のコンテナ"},
	"image.role_independent":        {"independent copy", "独立したコピー"},
	"image.role_host":               {"Host source for future copies", "今後のコピーに使うHost取得元"},
	"image.role_detached":           {"detached retained Store", "環境から切り離して保持しているOCI Store"},
	"snapshot.columns":              {"ID\tENVIRONMENT\tSTATE\tWORKSPACES\tOCI", "ID\t環境\t状態\tWorkspace数\tOCI"},
	"snapshot.created":              {"Snapshot %s (%s) for %q\n", "snapshot %s（状態: %s、対象環境: %q）\n"},
	"snapshot.deleted":              {"Snapshot deleted; current Environments, Workspace and OCI data retained", "snapshotを削除しました。現在の環境、Workspace、OCIデータは保持しています。"},
	"snapshot.write_failed":         {"haco: cannot write snapshot result", "haco: snapshotの処理結果を出力できません。"},
	"snapshot.restored_environment": {"Environment %s (%s)\n", "環境 %s（状態: %s）\n"},
	"snapshot.restored_workspace":   {"Workspace %s\n", "Workspace %s\n"},
	"snapshot.restored_oci":         {"OCI Store %s\n", "OCI Store %s\n"},
	"snapshot.restore_write_failed": {"haco: cannot write restore result", "haco: 復元結果を出力できません。"},
	"workflow.source_not_ready":     {"haco: source reference is not ready", "haco: コピー元Workspaceの準備が完了していません。"},
	"workflow.source_unavailable":   {"haco: source reference unavailable", "haco: コピー元Workspaceの情報を取得できません。"},
	"workflow.destination_unsafe":   {"haco: destination reference already exists or is unsafe; inspect it before retrying", "haco: コピー先の参照が既に存在するか、安全を確認できません。再試行前にコピー先を確認してください。"},
	"workflow.fork_ready":           {"Workspace fork ready; source stays stopped. Open the destination directory to create its Env.", "独立したWorkspaceのコピーを用意しました。コピー元は停止したままです。コピー先ディレクトリを開くと環境を作成できます。"},
}
