package cliui

var dailyCatalog = map[string]translation{
	"vscode.unknown":               {"unknown command %q", "不明なコマンド %q"},
	"approval.waiting":             {"[waiting_approval] %d pending request(s); no decision has been submitted.\n", "[waiting_approval] 承認待ちが%d件あります。回答は送信していません。\n"},
	"approval.terminal_required":   {"Approval remains pending. Use a terminal to review, or haco approve --list --json for scripts.", "承認待ちのままです。端末でhaco approveを実行して確認してください。スクリプトからの確認にはhaco approve --list --jsonを使います。"},
	"review.unconfirmed":           {"Local review ended without a confirmed result. Inspect current requests and Policy before retrying.", "承認の結果を確認できずに終了しました。再試行する前に、承認待ちの操作とPolicyを確認してください。"},
	"preview.select":               {"select an Environment by name; use haco env list", "haco env listで環境を確認し、名前を指定してください"},
	"preview.multiple":             {"multiple preview connections; close this port and reopen", "プレビュー接続が複数あります。このポートの接続を閉じてから開き直してください"},
	"preview.failed":               {"haco: preview:", "haco: プレビューを準備できません:"},
	"preview.closed":               {"Preview connection closed.", "プレビュー接続を閉じました。"},
	"preview.open_url":             {"haco: open the printed URL in your browser", "haco: 表示したURLをブラウザーで開いてください"},
	"preview.browser_failed":       {"haco: browser launch failed; open the printed URL in your browser", "haco: ブラウザーを起動できませんでした。表示したURLを手動で開いてください"},
	"experimental.locate":          {"haco: cannot locate configuration", "haco: 設定ファイルの場所を確認できません"},
	"experimental.warning":         {"Experimental: configuration compatibility is not guaranteed.", "実験的機能: 設定の互換性は保証されません。"},
	"experimental.file":            {"replace experimental.vscode with a YAML subtree file", "YAMLファイルでexperimental.vscodeの設定を置き換える"},
	"experimental.json":            {"print JSON; with -, replace from JSON stdin", "JSONを表示する。-を指定すると標準入力のJSONで置き換える"},
	"experimental.unconfirmed":     {"haco: experimental configuration was not acknowledged; inspect YAML before retrying:", "haco: 実験的設定の保存を確認できませんでした。再試行する前にYAMLを確認してください:"},
	"experimental.retained":        {"Edited subtree retained:", "編集した設定を保持しています:"},
	"experimental.editor_retained": {"Editor files retained:", "編集用ファイルを保持しています:"},
	"experimental.saved":           {"Saved experimental.vscode:", "experimental.vscodeを保存しました:"},
	"vscode.help":                  {"Open a Workspace in VS Code or remove its Environment", "WorkspaceをVS Codeで開く・対応する開発環境を削除する"},
	"vscode.open":                  {"Prepare SSH and open the Workspace in VS Code", "SSH接続を準備し、WorkspaceをVS Codeで開く"},
	"vscode.delete":                {"Delete the bound Environment; retain Workspace files", "対応する開発環境を削除する。Workspaceのファイルは保持する"},
	"vscode.workspace":             {"Exact Workspace directory on the trusted Host.", "信頼済みHost上のWorkspaceディレクトリ。"},
	"vscode.name":                  {"Environment name; omitted names are derived from the Workspace path.", "開発環境名。省略時はWorkspaceのパスから決まります。"},
	"vscode.read_only":             {"read-only Workspace", "Workspaceを読み取り専用にする"},
	"vscode.no_launch":             {"prepare SSH only", "SSH接続の準備だけを行う"},
	"vscode.path_required":         {"exact Workspace path required", "Workspaceのパスを1つ指定してください"},
	"vscode.binding_mismatch":      {"workspace binding mismatch", "指定した環境とWorkspaceが一致しません。対象を確認してください"},
	"vscode.ready":                 {"SSH ready:", "SSH接続の準備ができました:"},
	"vscode.usage":                 {"Use haco-vscode --help for available commands.", "haco-vscode --helpで利用できる操作を確認してください。"},
}
