package cliui

var commandCatalog = map[string]translation{
	"reclaim.failure":              {"Windows reclamation: %s failed at %s.", "Windows容量回収: %sの「%s」で失敗しました。"},
	"reclaim.phase.prepare":        {"preparation", "準備"},
	"reclaim.phase.launch":         {"worker launch", "回収処理の起動"},
	"reclaim.stage.registration":   {"WSL registration check", "WSLの登録確認"},
	"reclaim.stage.exclusion":      {"another operation check", "別の操作が動いていないかの確認"},
	"reclaim.stage.disk_path":      {"managed disk selection", "管理対象ディスクの選択"},
	"reclaim.stage.disk_access":    {"managed disk access", "管理対象ディスクへのアクセス"},
	"reclaim.stage.record_access":  {"saved result access", "保存結果へのアクセス"},
	"reclaim.stage.windows_owner":  {"Windows user check", "Windowsユーザーの確認"},
	"reclaim.stage.enrollment":     {"installation enrollment", "導入時の登録情報"},
	"reclaim.stage.installation":   {"installed WSL identity read", "WSL内の導入情報の読み取り"},
	"reclaim.stage.binding":        {"installation and disk correspondence", "導入情報とディスクの対応確認"},
	"reclaim.stage.intent":         {"operation record preparation", "実行前の記録"},
	"reclaim.stage.pin_executable": {"installed helper selection", "導入済み回収プログラムの確認"},
	"reclaim.stage.process_start":  {"Windows process creation", "Windows処理の作成"},
	"reclaim.stage.readiness":      {"worker startup acknowledgement", "起動した処理の応答確認"},
	"reclaim.stage.other":          {"an unclassified operation", "未分類の操作"},
	"reclaim.native_error":         {"Windows error code: %d", "Windowsエラー番号: %d"},
	"reclaim.inspect":              {"Inspect haco reclaim --status before another action. A failed launch response does not prove the worker never started.", "次の操作の前に haco reclaim --status で確認してください。起動応答の失敗だけでは、処理が始まっていないと断定できません。"},
	"reclaim.installation":         {"Reopen the selected Hacocoon installation and inspect haco doctor. Keep saved registration and disk data; do not replace them to bypass this check.", "対象のHacocoonを開き直し、haco doctor で確認してください。保存された登録情報やディスクを消したり差し替えたりせず、原因を確認してください。"},
	"reclaim.access":               {"Use the Windows account that installed this Hacocoon and inspect haco doctor. Retain the existing disk and saved result.", "このHacocoonを導入したWindowsアカウントで haco doctor を確認してください。既存ディスクと保存結果は残してください。"},
	"reclaim.existing":             {"Inspect haco reclaim --status. Let a live operation finish; use haco reclaim --review to retain a failed/interrupted result before a separate new run.", "haco reclaim --status を確認してください。実行中なら完了を待ち、失敗・中断なら haco reclaim --review で記録を保持してから、別の新しい操作を始めてください。"},
	"reclaim.attached":             {"Windows still reported this disk in use, so compaction was not started. Files remain. Inspect this saved result; use haco reclaim --review before a separate retry. Other WSL distributions are not stopped automatically.", "Windowsがディスクを使用中と報告したため、圧縮は始めていません。ファイルは残っています。保存結果を確認し、haco reclaim --review の後で別途再試行してください。他のWSLは自動停止しません。"},
	"cache.empty":                  {"Empty enrolled Env caches; retain Workspace, OCI and saved copies", "環境内の対象キャッシュを空にし、Workspace・OCI・保存コピーを保持する"},
	"cache.empty_usage":            {"Usage: haco cache empty [--preview] [--yes] [--json] <env> [<area>] | --all", "使い方: haco cache empty [--preview] [--yes] [--json] <env> [<area>] | --all"},
	"cache.empty_yes":              {"Confirm the displayed Env cache cleanup", "表示した環境内キャッシュの削除を確認済みとして実行"},
	"cache.empty_all":              {"Select enrolled caches in all Environments", "すべての環境の対象キャッシュを選択する"},
	"cache.empty_preview":          {"Show the scope without changing data", "データを変更せず対象だけ表示する"},
	"cache.empty_area":             {"%s / %s: %s; %s; saved copies retained: %d", "%s / %s: %s／%s／残る保存コピー: %d"},
	"cache.empty_warning":          {"Empty only the displayed Env cache contents. Stop these Envs first. Workspace, source, OCI, common generations and saved copies remain. This does not guarantee physical space recovery.", "表示した環境内のキャッシュ内容だけを空にします。先に対象環境を停止してください。Workspace・ソース・OCI・共通世代・保存コピーは残ります。物理容量の回収を保証する操作ではありません。"},
	"cache.empty_prompt":           {"Empty these Env caches? [y/N] ", "これらの環境内キャッシュを空にしますか？ [y/N] "},
	"cache.empty_cancelled":        {"Cancelled; Env cache data retained.", "中止しました。環境内のキャッシュを保持しています。"},
	"cache.empty_partial":          {"Cleanup is incomplete. Keep affected Envs stopped; inspect with cache empty --preview, then repeat with fresh confirmation. An interrupted clear blocks resume until empty contents are verified.", "掃除が未完了です。対象環境は停止したまま、cache empty --preview で確認してから改めて実行してください。途中の掃除は、空になったことを確認できるまで環境の再開を止めます。"},
	"cache.empty_done":             {"Selected Env caches are empty. Resume development to regenerate them; retained sources and saved copies remain.", "対象の環境内キャッシュを空にしました。開発を再開すると必要なデータが再生成されます。共通元と保存コピーは残っています。"},
	"cache.empty_none":             {"No enrolled Env caches selected.", "対象の環境内キャッシュはありません。"},
	"cache.state.clearing":         {"cleanup interrupted; explicit retry required", "掃除途中・確認して再実行が必要"},
	"cache.state.empty":            {"empty", "空になりました"},
	"cache.state.ready":            {"ready", "利用可能"},
	"cache.state.not_started":      {"not started", "未実行"},

	"cache.recover":                         {"Resume verified completed collection without copying again", "完了確認済みの収集をコピーし直さず復旧する"},
	"cache.recovered":                       {"Verified copies recovered. Current sources can be reused; unselected data remains available for reviewed clearing. Check cache status before resuming the producer.", "完了確認済みのコピーを復旧しました。選択中の世代は再利用でき、未選択のデータは確認してクリアできます。元の環境を再開する前に状態を確認してください。"},
	"cache.history":                         {"List retained collection attempts for a named area", "名前付き領域に残る収集データを確認する"},
	"cache.clear":                           {"Clear source generations while retaining existing Environment data", "既存環境のデータを保持して再利用元の世代をクリアする"},
	"cache.clear_yes":                       {"Confirm the displayed source-data cleanup", "表示した再利用元データの削除を確認済みとして実行"},
	"cache.maintenance_usage":               {"Usage: haco cache history|recover [--json] <env> <area> | clear [--yes] [--json] <env> <area> | history|recover|clear --all [--yes] [--json]", "使い方: haco cache history|recover [--json] <env> <area> | clear [--yes] [--json] <env> <area> | history|recover|clear --all [--yes] [--json]"},
	"cache.all":                             {"Include all cache reuse sources, including deleted producers", "元の環境が削除済みのものも含め、すべての再利用キャッシュを対象にする"},
	"cache.not_started":                     {"Not started; inspect the current state before retrying.", "未実施です。現在の状態を確認してから再操作してください。"},
	"cache.all_warning":                     {"Reset all displayed cache reuse sources and delete only their reviewed collected data. Existing Env copies, Workspaces, OCI and protected snapshots remain. This does not reclaim physical disk space by itself.", "表示した全キャッシュの再利用元をリセットし、確認した収集データだけを削除します。既存Envのコピー・Workspace・OCI・保護されたsnapshotは残ります。これだけで物理容量が戻るとは限りません。"},
	"cache.group":                           {"Cache group %d", "キャッシュ %d"},
	"cache.no_producer":                     {"Retained reuse source; no existing Environment provides a display name.", "保持している再利用元です。名前を照合できる既存Envはありません。"},
	"cache.independent_envs":                {"Independent copies remain in: %s", "独立したコピーを保持するEnv: %s"},
	"cache.history_title":                   {"%s: %s; current generation %d", "%s: %s／現在の世代 %d"},
	"cache.history_entry":                   {"%s; copied from generation %d; %s", "%s／コピー元の世代 %d／%s"},
	"cache.history_empty":                   {"No retained collection data for this area.", "この領域の収集データは残っていません。"},
	"cache.history_state.current":           {"selected for new Environments", "新しい環境の再利用元"},
	"cache.history_state.retained":          {"retained, not currently selected", "保持中・現在は再利用元に未選択"},
	"cache.history_state.creating":          {"collection incomplete", "収集が未完了"},
	"cache.history_state.deleting":          {"cleanup incomplete", "削除が未完了"},
	"cache.history_state.deleted":           {"deleted", "削除済み"},
	"cache.history_state.cleanup-required":  {"cleanup requires recovery; retained", "片付けに復旧が必要・保持中"},
	"cache.history_state.recovery-required": {"copy requires recovery; retained", "コピーに復旧が必要・保持中"},
	"cache.clear_warning":                   {"Clear this reuse source and delete its reviewed collected data. Existing Environment copies, Workspaces and OCI data remain. Shared sources affect new Environments in the whole group. Busy or uncertain copies remain owned.", "この再利用元をリセットし、表示した収集データを削除します。既存環境のコピー・Workspace・OCIデータは残ります。共有設定ではグループ全体の新しい環境に影響します。使用中や結果不明のコピーは保持します。"},
	"cache.clear_prompt":                    {"Clear this cache source? [y/N] ", "このキャッシュの再利用元をクリアしますか？ [y/N] "},
	"cache.clear_cancelled":                 {"Cancelled; collected data retained.", "中止しました。収集データを保持しています。"},
	"cache.cleared":                         {"Reuse source reset. New Environments start empty until a new producer collects; existing Environment data is unchanged. This is not physical disk reclamation.", "再利用元をリセットしました。次に作る環境は、新しい環境から収集するまで空のキャッシュで始まります。既存環境のデータは保持します。物理ディスクの容量回収とは別の操作です。"},
	"cache.clear_partial":                   {"Some data remains owned. Inspect history and retry clear after in-flight copies finish; unknown copies need recovery.", "一部のデータを保持しています。履歴を確認し、進行中のコピーが完了したらクリアを再試行してください。結果不明のコピーには復旧が必要です。"},
	"cache.clear_changed":                   {"The reviewed source changed or reset failed. Inspect history and review again before retrying.", "確認した再利用元が変わったか、リセットに失敗しました。履歴を確認し直してから再試行してください。"},
	"cache.file":                            {"Host JSON settings file with named areas and compatibility (up to 64 KiB)", "領域名と互換条件を記したHostのJSON設定ファイル（64 KiB以内）"},
	"cache.area_option":                     {"configured area name; omit to collect all enrolled areas", "設定した領域名。省略すると登録済みの全領域を収集"},
	"cache.state.cleanup-required":          {"candidate cleanup requires recovery", "収集中の領域の片付けに復旧が必要"},
	"cache.setting":                         {"%s: %s; compatibility %s; %s", "%s: %s／互換条件 %s／%s"},
	"cache.scope_workspace":                 {"one Workspace", "Workspaceごとに分離"},
	"cache.scope_shared":                    {"shared group %s", "共有グループ %s"},
	"cache.help":                            {"Configure and reuse caches produced in ordinary Environments", "通常の開発環境で作るキャッシュを設定・収集・再利用する"},
	"cache.settings":                        {"Show Host cache settings", "Hostのキャッシュ設定を表示する"},
	"cache.configure":                       {"Apply a JSON settings file to new Environments", "JSON設定を今後作る環境へ適用する"},
	"cache.status":                          {"Show enrolled areas and their source generations", "対象領域とコピー元・現在の世代を確認する"},
	"cache.collect":                         {"Publish whole cache areas from a stopped Environment", "停止した環境から領域全体を次の世代として収集する"},
	"cache.usage":                           {"Usage: haco cache settings | configure <file> | status <env> | collect <env> [area]; put --json before the target.", "使い方: haco cache settings | configure <file> | status <env> | collect <env> [area]。--jsonは対象より前に指定します。"},
	"cache.input":                           {"Cannot read cache settings. Use a regular JSON file up to 64 KiB with named areas and explicit compatibility.", "キャッシュ設定を読み込めません。名前付き領域と互換条件を記した64 KiB以内のJSONファイルを指定してください。"},
	"cache.failed":                          {"Cache operation failed. Inspect haco doctor and haco cache settings before retrying.", "キャッシュの操作に失敗しました。haco doctor と haco cache settings で確認してから再試行してください。"},
	"cache.configured":                      {"Settings saved for new Environments. Existing Environments keep their data and original selections.", "今後作る環境の設定を保存しました。既存の環境はデータと作成時の対象領域を保持します。"},
	"cache.none_settings":                   {"No cache areas configured. Configure reproducible directories before creating a new Environment.", "キャッシュ領域は未設定です。新しい環境を作る前に、再生成できるデータの保存先を設定してください。"},
	"cache.none_env":                        {"This Environment has no enrolled cache areas. Configure areas and create a new Environment.", "この環境には対象領域がありません。領域を設定し、新しい環境を作ってください。"},
	"cache.area":                            {"%s: %s; source %d, current %d; %s", "%s: %s／コピー元 %d・現在 %d／%s"},
	"cache.state.enrolled":                  {"enrolled", "収集対象"},
	"cache.state.published":                 {"published", "収集済み"},
	"cache.state.skipped":                   {"a newer generation already exists; local data retained", "新しい世代があるため見送り・環境内のデータは保持"},
	"cache.state.recovery-required":         {"recovery required; data retained", "復旧が必要・データは保持"},
	"cache.state.failed":                    {"failed", "失敗"},
	"cache.stop_first":                      {"Stop the Environment with haco env stop <env>, then collect again.", "haco env stop <env> で環境を停止してから収集してください。"},
	"cache.recovery":                        {"Collection is incomplete. Source and candidate remain owned; keep this Environment stopped. Automatic retry cannot confirm an unknown copy outcome.", "収集が未完了です。元データと収集中のデータを保持しています。環境は停止したままにしてください。結果が不明なコピーは自動再試行で完了扱いにできません。"},
	"cache.not_found":                       {"Environment or cache area not found. Check haco env list and haco cache status <env>.", "環境または対象領域が見つかりません。haco env list と haco cache status <env> で確認してください。"},
	"cache.next":                            {"New compatible Environments use independent copies. This Environment keeps its local data; file contents are never merged automatically.", "次に作る互換性のある環境で独立コピーを使えます。この環境のデータは残り、ファイル単位の自動マージは行いません。"},

	"help.daily.footer":                {"Options go before the target. Progress/diagnostics use stderr. Build/test in the Env after open. Blank terminal selection cancels; scripts should name the Env.", "オプションは対象の前に指定します。進捗と診断はstderrへ出力します。open後の環境でビルドやテストを実行してください。端末での未入力は中止です。スクリプトでは環境名を指定してください。"},
	"help.daily.delete":                {"Delete the Env rootfs; retain Workspace/OCI/snapshots", "環境のrootfsを削除し、Workspace・OCIデータ・snapshotを保持する"},
	"help.daily.stop":                  {"Stop work, keeping the Env and data", "環境とデータを残して停止する"},
	"help.daily.open":                  {"Open /workspace; use --client ssh for a shell", "/workspaceを開く。シェルを使う場合は--client sshを指定する"},
	"help.daily.start":                 {"Resume a stopped Environment", "停止していた環境を再開する"},
	"help.daily.status":                {"Inspect state and retained Workspace", "状態と保持している作業データを確認する"},
	"help.daily.list":                  {"Find yesterday's Environment", "前回の開発環境を探す"},
	"help.daily":                       {"Daily workflow (trusted haco-host or WSL/Linux Physical Host):", "日々の操作（信頼済みhaco-host、またはWSL/LinuxのPhysical Host）:"},
	"help.experimental":                {"Edit Experimental VS Code settings and extensions", "Experimental VS Codeの設定と拡張機能を編集する"},
	"command.ssh.cleanup":              {"Remove positively stale managed SSH targets", "無効になったことを確認できたSSH接続先を整理する"},
	"run.help":                         {"Run one command and remove its temporary Environment. Use -i for pipes or -it for a terminal. --workspace retains project files and OCI data; --json is available for captured output only.", "コマンドを実行し、一時Envを終了後に削除します。パイプは-i、端末は-itを使います。--workspaceで作業ファイルとOCIデータを保持できます。--jsonは出力をまとめて取得する場合に使います。"},
	"run.flag_workspace":               {"existing Workspace to retain (default: temporary)", "保持する既存Workspace（省略時は一時領域）"},
	"run.flag_readonly":                {"mount the selected Workspace read-only", "指定したWorkspaceを読み取り専用にする"},
	"run.flag_rm":                      {"remove the Environment after execution (always enabled)", "実行後にEnvを削除する（常に有効）"},
	"run.canceled":                     {"haco: execution canceled; controller cleanup was requested but is not confirmed here. Inspect haco env list.", "haco: 実行を中断しました。controllerへ片付けを要求しましたが、完了は未確認です。haco env listで確認してください。"},
	"run.truncated":                    {"haco: command output was truncated", "haco: 出力が長いため一部を省略しました。"},
	"run.cleanup_unknown":              {"haco: execution or cleanup failed; inspect Environment %s. Cleanup is not confirmed.", "haco: 実行または片付けに失敗し、片付け完了は未確認です。haco env status %sで確認してください。"},
	"run.no_result":                    {"haco: temporary execution failed before a result was received; inspect haco env list", "haco: 一時実行の結果を受け取れませんでした。haco env listで確認してください。"},
	"run.invalid_exit":                 {"haco: invalid command exit status", "haco: コマンドの終了値が不正です。"},
	"run.execution_failed":             {"haco: execution failed; Environment cleanup completed", "haco: 実行に失敗しました。Envの片付けは完了しています。"},
	"run.flag_input":                   {"stream standard input and output", "標準入力と出力を逐次転送する"},
	"run.flag_tty":                     {"open a terminal with input, editing and resize", "入力・編集・サイズ変更ができる端末を開く"},
	"run.stream_json":                  {"haco: interactive output cannot use --json; omit --json to stream, or omit -i/-t for a captured result", "haco: 対話出力と--jsonは併用できません。逐次出力なら--jsonを、結果をまとめて取得するなら-i/-tを外してください。"},
	"run.tty_required":                 {"haco: -t requires a terminal; use -i for piped input", "haco: -tには端末が必要です。パイプから入力する場合は-iを使ってください。"},
	"command.host":                     {"Use the trusted Host controller client", "信頼済みHostの操作窓口を使う"},
	"command.host.doctor":              {"Check the connection to the Host controller", "Hostの操作窓口との接続を確認する"},
	"command.env.exec":                 {"Run a command in an Environment", "環境の中でコマンドを実行する"},
	"command.env.shell":                {"Open an interactive shell in an Environment", "環境の中で対話シェルを開く"},
	"daily.unknown_state":              {"Completion is not confirmed; resource state is unknown until inspected. Do not assume cleanup or retry succeeded.", "完了は確認できていません。状態を確認するまで、削除や再試行が成功したと判断しないでください。"},
	"daily.inspect":                    {"Next: haco env status %s; haco doctor %s. Inspect before retrying or deleting retained data.\n", "次の操作: haco env status %s、haco doctor %s で状態を確認してください。再試行や保持データの削除は確認後に行ってください。\n"},
	"daily.ssh_policy":                 {"If the Base lacks sshd, SSH preparation needs package access under the current Env Policy. In trusted haco-host, inspect haco approve --list and haco config; review the package endpoints before changing Policy. No approval or package failure is inferred from this error.", "ひな形にsshdがない場合、SSH準備には現在の承認ルールでパッケージ取得が必要です。信頼済みhaco-hostで haco approve --list と haco config を確認し、取得先を確認してからルールを変更してください。このエラーだけでは承認やパッケージ取得の失敗と断定できません。"},
	"daily.journal":                    {"Diagnostics (WSL/Linux Physical Host, administrator): journalctl -u haco-controller.service --since '30 minutes ago' --no-pager", "詳細診断（WSL/LinuxのPhysical Host、管理者）: journalctl -u haco-controller.service --since '30 minutes ago' --no-pager"},
	"daily.confirmation":               {"No changes made: confirmation requires a terminal; review the target and use --yes for scripts.", "変更していません。確認には端末が必要です。スクリプトでは対象を確認したうえで --yes を指定してください。"},
	"daily.delete":                     {"Delete Env %q: removes its runtime/root filesystem and connections. Workspace files, OCI Stores and independent snapshots remain. Use stop to keep the Env for tomorrow.\n", "環境 %q を削除します。環境内のrootfsと接続を削除し、Workspace・OCIデータ・独立snapshotを保持します。環境も残して次回再開する場合はstopを使ってください。\n"},
	"daily.next_open":                  {"Next: haco open %s (desktop) or haco env status %s.\n", "次の操作: haco open %s で接続するか、haco env status %s で状態を確認してください。\n"},
	"daily.resume":                     {"Resume: haco env start %s, then haco open %s.\n", "再開するには haco env start %s、続いて haco open %s を実行してください。\n"},
	"daily.retained":                   {"Review retained data: haco workspace list; haco plugin oci store list; haco snapshot list.", "保持データの確認: haco workspace list、haco plugin oci store list、haco snapshot list。"},
	"notification.inspect_failure":     {"Inspect haco doctor, haco approve --list and haco config. Similar failures are grouped for one minute.", "haco doctor、haco approve --list、haco config で確認してください。同種の失敗通知は1分間まとめます。"},
	"command.env":                      {"Create, inspect and connect to development environments", "開発環境を作る・調べる・接続する"},
	"command.env.list":                 {"List development environments", "開発環境を一覧で確認する"},
	"command.env.create":               {"Create an environment with a required Workspace; OCI is automatic unless disabled", "作業場所を指定して環境を作る。OCIは自動準備、--no-ociで省略"},
	"command.env.status":               {"Inspect runtime state and retained working data", "環境の状態と保持している作業データを確認する"},
	"command.env.start":                {"Resume a stopped environment", "停止中の環境で作業を再開する"},
	"command.env.stop":                 {"Stop work and retain the environment and its data", "環境と作業データを残して停止する"},
	"command.env.delete":               {"Delete the runtime; retain Workspace, OCI data and snapshots", "環境を削除し、Workspace・OCIデータ・snapshotを保持する"},
	"command.env.ssh":                  {"Prepare portless SSH access using a client-owned public key", "クライアントの公開鍵でポート指定の不要なSSH接続を準備する"},
	"command.env.ssh-config":           {"Print SSH connection configuration", "SSH接続設定を表示する"},
	"command.env.disconnect":           {"Revoke an existing connection", "既存の接続を解除する"},
	"command.env.forward":              {"Forward a Physical Host loopback port; protocol defaults to TCP", "Physical Hostのloopbackから転送する。既定はTCP"},
	"command.env.copy":                 {"Independently copy a stopped environment and retained data", "停止中の環境と保持データを独立コピーする"},
	"command.env.export":               {"Export stopped managed data; destination defaults to <env>.haco", "停止中の管理対象データを書き出す。既定は<env>.haco"},
	"command.env.import":               {"Import independently; default name is <source>-imported", "独立した環境へ取り込む。既定名は<source>-imported"},
	"command.repo":                     {"Manage trusted Host source repositories", "信頼済みHostの取得元リポジトリを管理する"},
	"command.repo.clone":               {"Fetch one existing upstream branch into a source repository", "既存ブランチを取得して作業のコピー元にする"},
	"command.repo.list":                {"List source repositories", "取得済みのコピー元を一覧表示する"},
	"command.repo.delete":              {"Review and delete an unused source repository", "未使用のコピー元を確認して削除する"},
	"command.workspace":                {"Prepare, reopen and fork retained working sets", "保持する作業セットを準備・再開・分岐する"},
	"command.workspace.create":         {"Create independent working copies of registered repositories", "登録済みリポジトリから独立した作業コピーを作る"},
	"command.workspace.import":         {"Copy a local checkout or linked worktree into independent retained work", "手元のcheckout・linked worktreeを独立した保持作業へ取り込む"},
	"command.workspace.prepare":        {"Associate a directory with retained work without moving its files", "既存ファイルを移動せず、ディレクトリと保持作業を関連付ける"},
	"command.workspace.fork":           {"Fork one stopped working set into independent data", "停止中の作業セットから独立したデータへ分岐する"},
	"command.workspace.list":           {"List retained working data", "保持中の作業データを一覧表示する"},
	"command.workspace.delete":         {"Review and delete unreferenced working data", "参照されていない作業データを確認して削除する"},
	"command.git":                      {"Connect ordinary Git and review push proposals", "通常のGitを接続しpushの変更内容を確認する"},
	"command.git.connect":              {"Connect the environment to its registered Git source", "環境を登録済みのGit取得元へ接続する"},
	"command.git.pending":              {"List pending push proposals", "確認待ちのpushを一覧表示する"},
	"command.git.status":               {"Inspect the latest recorded push", "最後に記録したpushの結果を確認する"},
	"command.git.reconcile":            {"Observe the remote ref without repeating a push", "pushを再送せずリモートの現在位置を確認する"},
	"git.recovery.request":             {"Optional historical request identity; the default is the latest push for this environment.", "過去の要求を指定する場合の識別子。省略すると、このEnvで最後に要求したpushを確認します。"},
	"git.recovery.none":                {"No push is recorded for this selection.", "対象のpush記録はありません。"},
	"git.recovery.target":              {"Environment: %s  Repository: %s  Branch: %s", "Env: %s  リポジトリ: %s  ブランチ: %s"},
	"git.recovery.unconfirmed":         {"The original push result is unconfirmed. A failed or interrupted request may have changed the remote.", "元のpush結果は未確認です。失敗・中断した要求でも、リモートが変更されている場合があります。"},
	"git.recovery.confirmed":           {"The original push has a durable confirmation receipt.", "元のpushには送信確認の保存記録があります。"},
	"git.recovery.failed":              {"The original capability operation ended with an error; its failure is retained separately from remote observations.", "元のCapability操作はエラーで終了しています。リモート照合の結果とは別に、その失敗記録を保持します。"},
	"git.recovery.active":              {"This request is still active. Wait for its result before checking the remote.", "この要求は実行中または承認待ちです。終了してからリモートを確認してください。"},
	"git.recovery.matches-new":         {"The remote currently matches the proposed commit. This alone does not prove which push changed it.", "現在のリモートは提案したcommitと一致します。一致だけでは、どのpushが変更したかを断定できません。"},
	"git.recovery.matches-old":         {"The remote currently matches the previously observed commit.", "現在のリモートは送信前に確認したcommitと一致します。"},
	"git.recovery.absent":              {"The remote branch is currently absent.", "現在、リモートに対象ブランチはありません。"},
	"git.recovery.diverged":            {"The remote currently points to a different commit. Review it before another push.", "現在のリモートは別のcommitを指しています。次のpushの前に差分を確認してください。"},
	"git.recovery.next":                {"Use haco git reconcile <environment> for a fresh read, then fetch and review your branch. Another push requires a new policy decision; no write is retried here.", "haco git reconcile <Env名>で現在位置を確認し、fetchしてブランチを見直してください。次のpushには新しいPolicy判断が必要です。この操作では再送しません。"},
	"command.git.approve":              {"Approve the exact pending push; saving a scope is optional", "確認したpushだけを承認する。許可範囲の保存は任意"},
	"command.git.deny":                 {"Deny the pending push; saving a scope is optional", "確認待ちのpushを拒否する。拒否範囲の保存は任意"},
	"command.base":                     {"Choose or build starting contents for an environment", "環境のひな形を選ぶ・作る"},
	"command.base.list":                {"List available starting points", "利用できるひな形を一覧表示する"},
	"command.base.inspect":             {"Inspect a starting point and its revision", "ひな形とそのリビジョンを確認する"},
	"command.base.import":              {"Import an archive as an isolated reusable Base", "アーカイブを隔離した作成環境で再利用できるBaseに取り込む"},
	"command.base.build":               {"Build a Base using Packer HCL2 and external scripts", "Packer HCL2と外部スクリプトからひな形を作成する"},
	"command.base.delete":              {"Review and delete an owned unused Base image", "所有する未使用のひな形イメージを確認して削除する"},
	"command.snapshot":                 {"Save and restore independent stopped data", "停止中のデータを独立して保存・復元する"},
	"command.snapshot.create":          {"Save one stopped environment and its managed data", "停止中の環境と管理対象データを保存する"},
	"command.snapshot.inspect":         {"Inspect saved components and deletion blockers", "保存データと削除できない理由を確認する"},
	"command.snapshot.list":            {"List saved snapshots", "保存済みのsnapshotを一覧表示する"},
	"command.snapshot.restore":         {"Restore independent data into a new environment", "独立したデータを新しい環境へ復元する"},
	"command.snapshot.delete":          {"Delete one explicitly selected saved snapshot", "選択した保存snapshotを削除する"},
	"command.plugin":                   {"Use optional developer integrations", "任意の開発用連携を利用する"},
	"command.plugin.oci":               {"Inspect and manage optional retained container data", "任意のコンテナ保持データを確認・管理する"},
	"command.plugin.oci.store":         {"Manage retained container stores", "保持しているコンテナデータ領域を管理する"},
	"command.plugin.oci.store.list":    {"List retained stores", "保持データ領域を一覧表示する"},
	"command.plugin.oci.store.inspect": {"Inspect a retained store", "保持データ領域を確認する"},
	"command.plugin.oci.store.create":  {"Create an independent retained store", "独立した保持データ領域を作成する"},
	"command.plugin.oci.store.delete":  {"Review and delete an unused owned store", "所有する未使用の保持データ領域を確認して削除する"},
	"command.plugin.oci.image":         {"Inspect and remove container images", "コンテナイメージを確認・削除する"},
	"command.plugin.oci.image.list":    {"List images in the selected runtime", "選択したruntimeのイメージを一覧表示する"},
	"command.plugin.oci.image.delete":  {"Review selected images before explicit deletion", "選択したイメージを確認して削除する"},
	"command.network":                  {"Connect authorized services and inspect active connections", "許可したサービスへ接続し、接続状態を確認する"},
	"command.network.tcp":              {"Open a policy-controlled TCP listener", "承認ルールに従うTCP接続口を開く"},
	"command.network.udp":              {"Open a policy-controlled UDP listener", "承認ルールに従うUDP接続口を開く"},
	"command.network.list":             {"Inspect active connection authority and expiry", "接続の許可範囲と期限を確認する"},
	"command.network.revoke":           {"Revoke an active connection", "実行中の接続を取り消す"},
	"command.network.host":             {"Register explicitly selected Host services", "明示的に選択したHostサービスを登録する"},
	"command.network.host.list":        {"List registered Host services", "登録したHostサービスを一覧表示する"},
	"command.network.host.add":         {"Register an exact service address; this does not grant access", "正確なサービス宛先を登録する。登録だけでは通信を許可しない"},
	"command.network.host.remove":      {"Remove a registered service", "サービス登録を解除する"},
	"command.network.rule":             {"Set the reviewed network rule and lifetime", "確認した接続ルールと有効期限を設定する"},
	"command.aws":                      {"Use approved AWS operations", "承認されたAWS操作を利用する"},
	"command.aws.s3":                   {"List and download selected S3 objects", "選択したS3オブジェクトを一覧・取得する"},
	"command.aws.s3.ls":                {"List approved S3 objects using Host authentication", "Host側の認証で許可されたS3オブジェクトを一覧表示する"},
	"command.aws.s3.cp":                {"Download one approved object without overwriting a file", "承認したオブジェクトを既存ファイルを上書きせず取得する"},
	"command.ssh":                      {"Prepare desktop-owned SSH access", "デスクトップ側にSSH接続を準備する"},
	"command.ssh.setup":                {"Prepare desktop keys and settings; blank terminal selection cancels", "デスクトップの鍵と設定を準備する。端末の空選択で中止"},
	"command.open":                     {"Open or resume work; directory preparation requires explicit repositories", "作業を開く・再開する。新しいディレクトリでは取得元の明示が必要"},
	"help.example":                     {"Example:", "実行例:"},
}
